// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bhhpafsncrcqelpwwqxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaHBhZnNuY3JjcWVscHd3cXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjkwMzAsImV4cCI6MjA4OTg0NTAzMH0.-AYfd8Tii86iG4soOfc6fYgXVyx-mLrQXfGraoEA2GE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);